### ISSUE TITLE
goedata - display - error table

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#10]
@byezy : If there is an error in display, e.g. a file in the geodata table cannot be displayed, should this tool generate an error table? See test MXD for example (just pushed up).

**Comment by byezy** [comment]
I don't think so. If you can't add it you can't add it ArcGIS does not give any useful info as to what occured when adding fails. The display should report failures in the results, to further the investigation try to add it manually, the result will be the same... the only things that will fail are things that can't be added, or things that are corrupt. Out of the scope of this convenience tool.

**Comment by byezy** [comment]
Leave this up as a suggestion I think... if we find a fail table useful we could implement it, but I doubt it will be...

In the case of this test, the test was trying to add an mxd to an mxd !!! so it failed for obvious reasons.

**Comment by byezy** [comment]
put on the back burner, gonna close this
