### ISSUE TITLE
raster - transform - INVERT

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#101]
Question 1. How doe the INVERT option work? It should use the following formula (I think):
 f(x)=(Min+Max)-x (where x is the value being transformed)

Question 2. Is the function applied to the range of the template area (as defined in the 'Geoprocessing > Environment'? Or to the range of the original input data?

The range of the transformed grid is not correct (see 'transform_INVERT.mxd') in test.
![capture_transform_invert](https://cloud.githubusercontent.com/assets/4453449/24845499/dc4da70a-1df5-11e7-8093-b485622cd6d2.JPG)

**Comment by byezy** [comment]
1. see the code emailed. again decide what formula you want. 

2. arcpy sa raster algebra... need to ask esri.,, may not be possible to address this.

**Comment by byezy** [comment]
also. re q#2... are you asking if the tool clips the original data to the processing extent? I think it would need an explicit clip in this case as this tool applies arcpy raster algebra which seems to work on the whole dataset...

**Comment by TomWaterat** [comment]
Change formula to: 
ras = (raster_min + raster_max) - ras
