### ISSUE TITLE
raster - transform - NORMALISE

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#103]
Normalise should produce a range between 0-1.. I think the problem might be that the function is being applied to the range of the original input data instead of the template area (as defined in the 'Geoprocessing > Environment'). 

See transform_NORMALISE.mxd

![capture_transform_normalise](https://cloud.githubusercontent.com/assets/4453449/24845850/04bae826-1df9-11e7-9cc4-18fb250d1984.JPG)

**Comment by byezy** [comment]
check the code emailed, decide what formula you want...

**Comment by TomWaterat** [comment]
This is working OK.. Just need to update user manual to let users know that it will apply the function BEFORE clipping to the 'Geoprocessing - Processing Extent' set by the user.

**Comment by TomWaterat** [comment]
For reference when writing help...

![transform](https://cloud.githubusercontent.com/assets/4453449/25647659/4f63bd6a-3007-11e7-91cd-92304f3f5a76.JPG)

**Comment by TomWaterat** [comment]
See first comment.. This is still happening.

**Comment by TomWaterat** [comment]
Add to user manual
