### ISSUE TITLE
raster - teak values - NoData

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#104]
When you replace values (either below a min or above a max) with NoData.. -1 is used as NoData..  This should be a 'NoData' value. See 'teak values.mxd' in tests.
![capture_tweak-values_nodata](https://cloud.githubusercontent.com/assets/4453449/24848447/2b3d4550-1e0a-11e7-90f3-c5ed7c655a5f.JPG)

**Comment by byezy** [comment]
the arcpy.Describe function was returning the wrong value !@#$@ anyway the raster object holds the correct value. should be right now

**Comment by TomWaterat** [comment]
No data value is being set to '65535' instead of -1.. This is not being picked up as NoData by ArcMap. See last run in Test MXD Results.
![tweakvaluesbug](https://cloud.githubusercontent.com/assets/4453449/25569439/e4c28fac-2e5a-11e7-8d68-3d37b38683c5.JPG)

**Comment by byezy** [comment]
Ok so explicitly casting the ndv to int seems to have worked. the tool still crashes on my machine when run in background, pls try yr end. test result and code is up.

**Comment by TomWaterat** [comment]
ArcMap did not crash (when run in background).. But NDV is still not being set to 65535.

**Comment by TomWaterat** [comment]
All good.
