### ISSUE TITLE
raster - Lookup_by_table

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#108]
Error - "takes 3 arguments, given 5". See MXD.

**Comment by byezy** [comment]
code to fix this pushed up. hope ok but can't run the test mate can't get an advanced license at the mo...!!!

**Comment by TomWaterat** [comment]
Working.. Processes all fields but still returns a Fail table.. ?? I can't see from the error message what field is causing the fail?? 

Error message reads:
File"C:\Data\gg3\grid-garage-3\tools\raster\lookup_by_table.py",line47,inlookup,out=Lookup(ras,f),Failedtoexecute.Parametersarenotvalid.,ERROR000864:Lookupfield:Theinputisnotwithinthedefineddomain.,ERROR000889:Invalidfieldtype.,Failedtoexecute(Lookup).

**Comment by byezy** [comment]
So this is obviously the ArcGIS call not liking one of the fields. this is not the same issue, should be a new one... but first check again the fields it has been fed, that has always been the source of this error in the past... meantime I will try to improve the error message

**Comment by byezy** [comment]
just pushed up code to improve err msg

**Comment by byezy** [comment]
oid fields!
![lup](https://cloud.githubusercontent.com/assets/4742942/25464903/63aa9d8a-2b42-11e7-91f7-efe55b7fdbe9.PNG)

**Comment by TomWaterat** [comment]
New error reporting is working. Tells you which field failed! Good one!
