### ISSUE TITLE
geodata - rename (error message when name is the same)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#11]
When the file name does not change it triggers an error message - which is fine.. @byezy Would it be possible to include the error message i.e. 'Error is caused by file name being the same', in the 'fail' output table? I've updated the 'geodata - rename' test files.
![error message](https://cloud.githubusercontent.com/assets/4453449/20086058/8ce299b6-a5c1-11e6-892b-1e745ced25a7.JPG)

**Comment by byezy** [comment]
@TomWaterat mate the gdb did not have most of the tables for the test... I have removed the missing tables and pushed it back up for next test... I am looking at the message code now it applies to every tool so hopefully can improve it

**Comment by byezy** [comment]
The message has been improved, where there were line breaks there are now pipes
