### ISSUE TITLE
geodata - select

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#113]
Only first item being added to results table. see mxd.
![select](https://cloud.githubusercontent.com/assets/4453449/25601406/289359f8-2f2f-11e7-9414-4ea3f112a0e8.JPG)

**Comment by byezy** [comment]
bug arose from adding proc_hist field, updated a basetool call to fix. tests ok this end. test up.

**Comment by TomWaterat** [comment]
All good now..
