### ISSUE TITLE
geodata - list workspace tables

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#114]
Returns 'No Tables Found' (see MXD) .. With the new 'prefix/suffix' feature maybe this is not needed?

**Comment by byezy** [comment]
where's the test? am I looking for a fail table from model builder bob? where is it in the tests repo?

**Comment by byezy** [comment]
??? anyway, just pushed up a test this end. BUT I do not see the prefix/suffix options for this tool??? U confused or me???

**Comment by TomWaterat** [comment]
Nailed!
