### ISSUE TITLE
metadata - create tips table (or 'export tips'?)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#129]
New functionality that uses geodata-describe fields (e.g. $general_dataType$) is working fine! Awesome!
But the 'tip_order' field does not list the fields in the correct order. See screen grab below..

![ggbugtiporder](https://cloud.githubusercontent.com/assets/4453449/26430525/45c22392-4131-11e7-829e-c4e20ff5badf.JPG)

**Comment by byezy** [comment]
tip_order fixed now

**Comment by byezy** [comment]
this the csv I used for testing...
[MASTER TIP TEMPLATE_OEH_with common info2.zip](https://github.com/NSW-OEH-EMS-KST/grid-garage/files/1030647/MASTER.TIP.TEMPLATE_OEH_with.common.info2.zip)

**Comment by TomWaterat** [comment]
Working now
