### ISSUE TITLE
gg release versions

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#130]
This is just an idea for discussion. I think metadata is really important.. but there's a risk we could get bogged down trying to update ESRI's data metadata. 

To manage this risk can we consider releasing GG v3.1 and 3.2 with the following features:

v3.1
-Remove all metadata and history logging (comment out?)
-Finalise all Metadata (toolbox) tools
-Complete all tool help 
-System test all tools

v3.2
-Implement metadata procedure logging functionality. i.e. write into the ESRI data metadata processing history field
-System test all tools

**Comment by byezy** [comment]
Ok that can work. 
But I think in 3.1 you should add:
-Move help to wiki or github pages, i.e. axe .docx help (should never release docx anyway, should have previously been published as pdf...)

**Comment by TomWaterat** [comment]
OK cool.. will move ALL help to wiki.. docx/pdf are history!

**Comment by byezy** [comment]
yep, I reckon should be able to do a 'save docx as html'? then simply whack it in the pages I reckon 0 or wiki whatever is easiest. ill have a play some time see what's easiest. as far as future dev on 3.2 goes I think we should discuss that a bit more...

**Comment by byezy** [comment]
3.1 must be looking good soon?

**Comment by TomWaterat** [comment]
Almost there! Still need to 1) fix bugs.. 2) create test models for new tools 3) add help to new GG tools and 4) move all help to wiki.. Aiming to finish by early next week all being well!

**Comment by byezy** [comment]
closing, as we will now use milestones to manage this...
