### ISSUE TITLE
tools that don't work when 'background processing' is turned on

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#131]
Is it possible to force running in foreground for JUST those tools that CANNOT be run in background (when background processing is turned on in the Geoprocessing Options?

**Comment by byezy** [comment]
All metadata tools can now only be run in the foreground. At least it keeps consistency for this toolset. They are generally very quick-finishing tools anyway.

**Comment by TomWaterat** [comment]
Cool! Thanks Dave. Working fine. :)

**Comment by TomWaterat** [comment]
Sorry Dave.. 'metadata > export XML' is not running in background when Geoprocessing Options is set to background processing..

**Comment by byezy** [comment]
Yes isn't that what you wanted? As above, all md tools can only run f/g now.... wot u want??

**Comment by TomWaterat** [comment]
Not true.. they are still running in the background.

**Comment by TomWaterat** [comment]
All fields are now text in Geodata table.. need to let users know in user manual.
