### ISSUE TITLE
ERROR 000824: The tool is not licensed.

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#137]
Not urgent, intermittent & unpredictable error, but would make testing easier if it didn't happen..
When I try and batch run the GG test models using Model Builder I get this error "ERROR 000824: The tool is not licensed.".. The weird thing is that each model works fine if I run it individually?!?!?@?#?

I found this from the following web site: https://gis.stackexchange.com/questions/54044/arcgis-error-000824-the-tool-is-not-licensed-in-arcpy

"Wrap the part of your code that needs spatial analyst extension as follows

arcpy.CheckOutExtension("spatial")
  your code
arcpy.CheckInExtension("spatial")

By checking out licenses only when you need them and checking them in, you won't hold up licences if other people need to use them. This is useful in a setting where there are fewer licenses than the people who use them in a network environment."

Also this ESRI page: http://desktop.arcgis.com/en/arcmap/latest/analyze/python/access-to-licensing-and-extensions.htm

**Comment by byezy** [comment]
yeh I don't think this is a good idea. nor do I see it as a bug. it will need a lot of testing. I can see this just creating difficult bugs. I am wondering if you can explicitly checkout several instances of a license without issue, if checking them back in during a script might mean losing the license... lotsa q's... keep this low priority until major issues arise.

**Comment by TomWaterat** [comment]
Agree! I actually haven't had that error for a while now.. fingers crossed it's gone.. I reckon close for now and re-open if it happens again.
