### ISSUE TITLE
Idea for a new tool: 'raster - zonal stats as table' (not high priority)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#142]
John Young rang me about a Model Builder question.. But I think the analysis he's doing could be done by Grid Garage tool. He wants to report on the 'Mean' of each input raster for each 'zone' in another raster. We had a similar tool in GG2 which reported on areas for each zone.

Follow up if time permits.

The red arrow points to the input raster being reported on that would be pulled from the 'geodata > search' results table.

![zonalstatsastable](https://user-images.githubusercontent.com/4453449/27463730-c509440e-580c-11e7-94d8-cbb57eff0ca4.JPG)

**Comment by byezy** [comment]
tool is in, state needs review

**Comment by TomWaterat** [comment]
This tool requires two GIS inputs.. One that defines the zone to report on (this can be either a raster or a feature class) for each input raster.. So the input value raster will be sourced from the 'table for rasters' input..
![gg_input rasterzone or featurezone](https://user-images.githubusercontent.com/4453449/29008223-6b63042c-7b56-11e7-8279-f06719ab9086.JPG)

**Comment by byezy** [comment]
like to leave this to 3.2, it's gonna be a lotta testing.

**Comment by byezy** [comment]
Do you want the option of specifying a field in the input table for zone data? It would need a string like:

"c:\blah\blah.shp: FID"  that would specify the DS and the field. Having a field for the zone field in the input table is a little much I think.

i.e. The user could feed a single DS for zones, or have different ones for each dataset... might try it if not too much hass n see what u reckn.

**Comment by byezy** [comment]
Branch i142 for testing. 

Will make new debug test repo, and ring you re a better test workflow...

**Comment by TomWaterat** [comment]
Priority = Medium (I might have time to test this next week)

**Comment by byezy** [comment]
This tool has been around for a while, so I am closing this for now
