### ISSUE TITLE
output table workspace

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#147]
be nice when using tiffs to provide a separate ws for the output tables thatn rasters - only because output to a gdb allows selection in tables. Currently, to use selections csv must be exported.

**Comment by TomWaterat** [comment]
Agree!! Another cool feature would be the ability to specify the output location in the input table.. i.e. a field with the output path.. Just an idea at the moment.. not high priority.

**Comment by byezy** [comment]
the branch for this is **dset-wspace**.
code is in, requires testing

**Comment by TomWaterat** [comment]
I changed branches but didn't notice any difference in the GUI.. See below.. did I use the correct github command?
![gg_github_branch](https://user-images.githubusercontent.com/4453449/29008727-235e09d4-7b5f-11e7-83de-1318b0343aaa.JPG)

**Comment by TomWaterat** [comment]
Tested in one tool and works ok.. will work into tool test models and raise issue if any tool fails..
