### ISSUE TITLE
Polygon to Raster tool

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#149]
The 'Feature > Rasterise by Table' tool currently uses the following ArcGIS tool:

Feature to Raster: http://desktop.arcgis.com/en/arcmap/10.3/tools/conversion-toolbox/feature-to-raster.htm

But this tool does not allow you to set any of the options relating to how it converts polygons to rasters. Could we add another variation of this tool that uses the following ArcGIS tool:

Polygon to Raster: http://desktop.arcgis.com/en/arcmap/10.4/tools/conversion-toolbox/polygon-to-raster.htm

This tool gives you the following options for the 'cell_assignment (Optional)' parameter:

"The method to determine how the cell will be assigned a value when more than one feature falls within a cell.
 #1 CELL_CENTER —The polygon that overlaps the center of the cell yields the attribute to assign to the cell.
  #2 MAXIMUM_AREA —The single feature with the largest area within the cell yields the attribute to assign to the cell.
  #3 MAXIMUM_COMBINED_AREA — If there is more than one feature in a cell with the same value, the areas of these features will be combined. The combined feature with the largest area within the cell will determine the value to assign to the cell."

Screen grab .. for discussion..
![screen grab - properties](https://user-images.githubusercontent.com/4453449/28100179-f078a700-6703-11e7-96df-3acf12a7d7c5.JPG)

**Comment by byezy** [comment]
First draft need testing

**Comment by byezy** [comment]
implemented. now for tests
