### ISSUE TITLE
raster - aggregate (but #1)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#15]
@byezy Replicate using aggregate mxd.. Note also pushed up a new sample data containing a smaller study area for the high res SPOT (5m) data set.

**Comment by byezy** [comment]
no aggregate test...

**Comment by TomWaterat** [comment]
@byezy Tested with same result.. Can you check the code was pushed up.

**Comment by TomWaterat** [comment]
@byezy Tool executes OK.. But the output raster is the wrong resolution, it is 5m instead of 30m (6 x 5m).  I ran the ArcGIS Aggregate Tool to confirm that the output should be 30m (see screen grab).  The Environment Variable 'Raster Analysis' cell size is set to 5m - which is correct, I think it's using this.
![gg_bug 3](https://cloud.githubusercontent.com/assets/4453449/20156314/fdbee26c-a723-11e6-8319-f493b5987fd0.JPG)

**Comment by byezy** [comment]
can u update the test for me so i can see your inputs... cheers

**Comment by TomWaterat** [comment]
@byezy Done

**Comment by byezy** [comment]
@TomWaterat , looking like an esri bug mate. Can you check the test... though the raster reports a cell size = 5, if you measure it it seems 30m and is identical with the output from the base gp tool (aggregate). I believe at this stage the aggregate tool (python wrapped) is not correctly updating metadata. I did an export to see if it would fix it but still same 30m size reported as 5m! See if it looks that way to you. cheers

![untitled](https://cloud.githubusercontent.com/assets/4742942/20158008/ffd5911a-a72b-11e6-9dbc-34a9b722c006.png)

**Comment by TomWaterat** [comment]
@byezy Bloody ESRI.. If there's no fix we'll just have to let users know and they'll have to do a Resample.. No big deal really.
