### ISSUE TITLE
feature - feature to raster

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#157]
Bug. Replicated in test repo (C:\Data\dirtydebug_keep_small\feature-feature_to_raster)

Error message:
![gg_feature-feature_to_raster](https://user-images.githubusercontent.com/4453449/28851390-6c5b93e8-7765-11e7-841c-d2762fe53902.JPG)

**Comment by byezy** [comment]
pls check fix

**Comment by TomWaterat** [comment]
Yay! Working!
