### ISSUE TITLE
metadata - audit

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#159]
Failing on row three of input geodata.  See test in repo: 

C:\Data\grid-garage-small-tests\metadata-audit

**Comment by byezy** [comment]
yeh not sure this tool was finished. did you ever use it in your workflow... I think it became redundant...???

**Comment by TomWaterat** [comment]
Look at for GG 3.2

**Comment by TomWaterat** [comment]
Priority = Low (not sure if I'll have time to review)

**Comment by byezy** [comment]
it appears this tool was dropped for some reason... closing this for now as it seems to not have been needed in last 18mths
