### ISSUE TITLE
Raster > Reclass By Threshold

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#161]
Thought we had working... I may have lost some code, the version I now have is definitely broken... need to address...

**Comment by byezy** [comment]
IF it can be found, include in 3.2

**Comment by byezy** [comment]
have opend branch i161 for this

**Comment by byezy** [comment]
Branch 161 for testing. Input table needs a field for remap string eg."0 10 1; 11 20 2", will try to push my test up.

**Comment by byezy** [comment]
![repodebug](https://user-images.githubusercontent.com/4742942/29756709-4d860ece-8be9-11e7-8eb7-45a676e60e07.PNG)
Test from here...

**Comment by TomWaterat** [comment]
Is this in 'master' now??

**Comment by byezy** [comment]
old. closing
