### ISSUE TITLE
GG WIKI: dealing with errors and crashes

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#162]
should be dealing with **issues** lets go a little 'Microsoft' here...

**Comment by TomWaterat** [comment]
Can you give me a call to discuss what you mean by this one?

**Comment by byezy** [comment]
"issues and undocumented features" not "errors and crashes"

**Comment by TomWaterat** [comment]
[Done](https://github.com/NSW-OEH-EMS-KST/grid-garage/wiki/Issues-and-undocumented-features)
