### ISSUE TITLE
raster - polygon to raster

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#163]
Would it be possible to default to "NONE" for the 'Priority' parameter (for all input feature classes)?

I did try using the 'Hectares' field for the 'VegBorderRiversGwydir_Comp09_VIS3801' and it worked ok..
  
![gg_feature-polygon_to_raster_04](https://user-images.githubusercontent.com/4453449/29008575-9c73cf0a-7b5c-11e7-801f-efae89a30247.JPG)

**Comment by byezy** [comment]
closed

**Comment by TomWaterat** [comment]
Re-opened as #164
