### ISSUE TITLE
Decorator parameters for Input table field defs

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#164]

**Comment by byezy** [comment]
The way the parameters for the input table fields are defined in the decorators has become messy and unclear. Needs refactoring. Thinking about a dict and keywords.

**Comment by TomWaterat** [comment]
Priority = High (if you think this will help other programmers to understand code).. Also will involve re-testing I presume.

**Comment by byezy** [comment]
done
