### ISSUE TITLE
Remove unfinished/tested tools for 3.1 release

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#166]
Tools to remove from current config
-

**Comment by TomWaterat** [comment]
Remove the following tools from 3.1 (Bring in for 3.2 if needed)
1. Metadata > Audit
2. Metadata > Get IAR ID from XML
3. Metadata > Import Metadata
4. Raster > Reclass by Threshold
5. Raster > Slice
6. Raster > Zonal Statistics as Table

**Comment by byezy** [comment]
removed
![capture](https://user-images.githubusercontent.com/4742942/29098862-057c09a2-7ce5-11e7-83e0-f88cfe20e791.PNG)

**Comment by TomWaterat** [comment]
Great! I'll start updating the XML help files now.
