### ISSUE TITLE
raster - values to points

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#169]
What is this field (Field for query) for? I couldn't find referenc e to it in the [ESRI help](http://desktop.arcgis.com/en/arcmap/latest/tools/spatial-analyst-toolbox/extract-values-to-points.htm). 
![gg_valuestopoints2](https://user-images.githubusercontent.com/4453449/29056413-31cac5e2-7c46-11e7-9cf4-21fe10b313fa.JPG)

**Comment by byezy** [comment]
Its an enhancement to the raw tool.
The field holds a query expression that's applied to the point feature class before the extraction...
It can be left blank and unused, will be most of the time perhaps but neded it for Mal's work...

**Comment by TomWaterat** [comment]
Can you provide an example of a query? How would the user generate it?

**Comment by byezy** [comment]
http://resources.arcgis.com/en/help/main/10.1/index.html#//00s500000033000000

**Comment by TomWaterat** [comment]
Thanks.. added link to Wiki
