### ISSUE TITLE
values - raster to points

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#172]
Error message.. Replicated in:

C:\Data\grid-garage-small-tests\raster-values-to-points\raster-values-to-points.mxd

You'll need to pull in the following two reppos:

C:\Data\grid-garage-small-tests
C:\Data\grid-garage-sample-data (for input grids)

**Comment by byezy** [comment]
Please test this part. But there is still a bug with this tool... for some reason output tables are made ok but at the last they are not setting in the output parameter... not obvious lets leave this as a lower priority bug until it becomes an issue

**Comment by byezy** [comment]
test is pushed back

**Comment by byezy** [comment]
and to make less confusion, renamed to "Extract Values at Points" = Esri name for their tool.

**Comment by TomWaterat** [comment]
Bug is due to a floating point input raster (UPDATE MANUAL TO THIS EFFECT).. otherwise working ok.
