### ISSUE TITLE
Metadata > Export Metadata 

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#173]
How do I explain the 'Style Sheet' user input [in the Wiki?](https://github.com/NSW-OEH-EMS-KST/grid-garage/wiki/Metadata-Tools-Export-Metadata) I couldn't find it in the [ESRI Help](http://desktop.arcgis.com/en/arcmap/Latest/tools/conversion-toolbox/export-metadata.htm)

![gg_metadata_export_metadata](https://user-images.githubusercontent.com/4453449/29255704-2a9d5640-80e7-11e7-8629-f968543bae9e.JPG)

**Comment by byezy** [comment]
Want me to rename the par to "Translator Style Sheet"?

**Comment by TomWaterat** [comment]
Nah.. Gotta draw the line.. I can't be bothered changing the documentation.. It's clear form the help what it its.. I'll change it to a 3.2 milestone.

**Comment by byezy** [comment]
for testing, branch i173
