### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#174]
https://github.com/NSW-OEH-EMS-KST/grid-garage/wiki/Why-use-the-Grid-Garage-Toolbox%3F

... processing step -> steps  ?

This approach differs slightly from normal batch processing in ArcGIS, instead of manually selecting single items or a folder on which to apply a tool or model you provide a table listing target datasets.
->
This approach differs slightly from normal batch processing in ArcGIS; instead of manually selecting single items or a folder on which to apply a tool or model you provide a table listing target datasets and tool parameters.

**Comment by byezy** [comment]
https://github.com/NSW-OEH-EMS-KST/grid-garage/wiki/Adding-Grid-Garage-to-the-ArcMap-ArcToolbox

The link is to the 'KST Github home page'

**Comment by byezy** [comment]
https://github.com/NSW-OEH-EMS-KST/grid-garage/wiki/How-does-Grid-Garage-work%3F

Each Grid Garage tool requires you to specify an input table (the Results table containing the list of geodata you want processed) and an output table name and location, as shown in the figure below.

Blehhh wot dat?


Each Grid Garage tool requires you to specify an input table (commonly the Results table output from a previous tool) containing the list of geodata you want processed and an output table name and location, as shown in the figure below.

**Comment by byezy** [comment]
https://github.com/NSW-OEH-EMS-KST/grid-garage/wiki/How-does-Grid-Garage-work%3F

When using the Grid Garage tools, the first step always involves generating a Results Table using the Geodata > Search tool, which is essentially a list of paths for the geodata items you want processed by a Grid Garage tool.

Mmmm nah there are other ways...

When using the Grid Garage tools, you need an input table holding links to geodata (geodata table TOM GLOSSARY?) So in carrying out a processing workflow the first step always involves selecting or generating an initial geodata table. Options:
- Use the  Geodata > Search or Geodata > Select tools which tabulate datasets (i.e. they list geodata sources) - items you may want processed by further Grid Garage tools.
- Use a geodata table from any previous Grid Garage tool (except Geodata > Display) run in previous work.
- Use other applications to generate simple CSV tables of geodata (for example at the command line piping the output of a directory listing program into a valid  CSV file). The Grid Garage tools support 'foreign' tables through the "Field for geodata" field input parameter that derives from the schema of the input geodata table.

**Comment by TomWaterat** [comment]
Thanks for the feedback Dave.. Wiki has been updated.
