### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#175]
Do we have a section for this ? Sorry if i missed it...

**Comment by byezy** [comment]
I see a bit in the "using gg" section but what about a link to arcgis sys requirements and a little matrix listing tools and the license or extension required to run it...

**Comment by byezy** [comment]
Would also be good to ask esri about python toolbox compatibility according to mr dangermond... perhaps hass support?

**Comment by TomWaterat** [comment]
Good idea.. Will do for 3.2 .. if we have time.

**Comment by TomWaterat** [comment]
Priority = Medium

**Comment by byezy** [comment]
old. closing
