### ISSUE TITLE
Output workspace field

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#176]
In addition to FIELD FOR GEODATA have a FIELD FOR OUTPUT WORKSPACE parameter as a standard input.

The parameter is Optional.
Default value is NONE.

If the user specifies a field the tools will see if it is a valid workspace, if it is the output goes there if not it falls back to the standard RESULT WORKSPACE value.

**Comment by TomWaterat** [comment]
Priority=Low - Leave as v4.0

**Comment by byezy** [comment]
my stupid idea. no longer like it. closing
