### ISSUE TITLE
Geodata > Display: Optional parameter for output table

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#177]
There was a time or two where I fed selections into this tool and then lost them. This parameter may help a QC proc branch where random rows from a large result table are selected for display. See any issues and the table is there for a describe etc etc. Also would bring it in line with every other tool... there's always one in a crowd...

**Comment by byezy** [comment]
What might be easy is to simply add the output table so exactly like other tools, then add a checkbox "do no write result table" which defaults false (usual case) but can be enabled when we want..

how does that sound?

**Comment by TomWaterat** [comment]
Priority = Medium - If that's a quick job.. otherwise re-allocate to v4.0.

**Comment by byezy** [comment]
lets close for now. idea for future versions.
