### ISSUE TITLE
raster - calculate statistics (bug #1)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#18]
@byezy I think the same bug is occuring here... see screen grab.. I'll wait until you've fixed the other tools before testing again.. 
![gg_bug 1](https://cloud.githubusercontent.com/assets/4453449/20127895/adacfa8e-a697-11e6-9f7c-8992eecf54ce.JPG)

**Comment by byezy** [comment]
@TomWaterat   yeh  mate some older tools not yet updated with changes. this tool should be fixed, may not find these until testing but easy fixes...

**Comment by TomWaterat** [comment]
@byezy Tried testing this tool by deleting the XML files.. Running the tool did not create the XML files or any statistics.. Can you suggest a better way to test this tool?

**Comment by byezy** [comment]
???  can u update the test so i can see what is going on... cheers

xmls will only appear in folders, not gdbs...

**Comment by TomWaterat** [comment]
@byezy Working OK now .. close
