### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#182]
With the possibility of external code contributors (c'mon guys) the code base needs to be properly documented. Not done to date as was not known if this would become necessary.

Will most likely use sphinx or similar but the main task should be to get some explanatory comments in the base .py files.

This will not include doc'ing every tool at this stage.

An overview doc showing how to develop a tool will be simple but essential.

**Comment by TomWaterat** [comment]
This would be awesome Dave.. If you have the time. Thanks

**Comment by byezy** [comment]
old. won't happen. closing
