### ISSUE TITLE
raster - clip (bug #1)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#19]
@byezy 
1) You might have to take me through this tool.. Can you specify an exent OR a polygon file?
2) Bug 1 - When you open the search gui to find a polygon - no polygon files come up.. see screen grab..
![gg_bug 2](https://cloud.githubusercontent.com/assets/4453449/20128039/2b8c760e-a699-11e6-8889-f1cc5091b991.JPG)

**Comment by byezy** [comment]
@TomWaterat 
mate the polygon filter should be fixed. Check the link below then call to discuss...

http://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/clip.htm#C_GUID-D4B6E476-CD4C-4BAD-A082-F698D0CDEDA6

**Comment by TomWaterat** [comment]
@byezy trying to push.. but bloody ESRI has it's claws on a the LOCK file.. I can't delete it.. will have to restart computer ..DOH!

**Comment by TomWaterat** [comment]
Crashed.. Diagnose and replicate bug with MXD.

**Comment by byezy** [comment]
you will still be able to poke holes on this tool perhaps. I have got it running but not tested every combo of inputs etc. Any new problems please create a new issue this one is now not relevant. cheers

**Comment by TomWaterat** [comment]
Tested and working
