### ISSUE TITLE
test that all tools use correct field for 'geodata'

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#200]
Geodata - generate names was hard-wired to use the 'geodata' field for source data.. change to using the field specified in the GUI. Test other tools for this bug..

**Comment by byezy** [comment]
generate names IS hardwired to use 'geodata', nothing has changed.
![capture](https://user-images.githubusercontent.com/4742942/30992034-13b03dda-a4eb-11e7-8d23-9ff1aebb1c71.PNG)

**Comment by byezy** [comment]
closing
