### ISSUE TITLE
geodata - display

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#204]
getting error.. see screen grab: let me know if you can't replicate..
![gg_bug_display](https://user-images.githubusercontent.com/4453449/31110777-2124824c-a855-11e7-9304-4fff2af4b041.JPG)

**Comment by byezy** [comment]
![capture](https://user-images.githubusercontent.com/4742942/31151216-2af6e994-a8e2-11e7-98ca-559d70c0a75f.PNG)

**Comment by TomWaterat** [comment]
Working now
