### ISSUE TITLE
geodata - list workspace tables

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#205]
See screen grab: .. let me know if you can't replicate..
![gg_bug_list](https://user-images.githubusercontent.com/4453449/31110882-d1cd75c2-a855-11e7-8340-008fc6884c26.JPG)

**Comment by byezy** [comment]
![capture](https://user-images.githubusercontent.com/4742942/31149787-db2b5c4c-a8dc-11e7-8264-1611bd9b125b.PNG)

there ARE NO TaBLES in that folder, at least not in my local repo...

**Comment by TomWaterat** [comment]
working
