### ISSUE TITLE
geodata - select

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#207]
errors.. see screen grab.. let me know if you can't replicate..
![gg_bug_select](https://user-images.githubusercontent.com/4453449/31205481-63066cc0-a9bd-11e7-9547-d16773d8693e.JPG)

**Comment by byezy** [comment]
![capture](https://user-images.githubusercontent.com/4742942/31205996-e5fb27a8-a9c0-11e7-8204-0974ca9656ee.PNG)

**Comment by byezy** [comment]
also checked the four other tools that use this call...

**Comment by TomWaterat** [comment]
Working OK
