### ISSUE TITLE
raster - set value to null

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#213]
See error:
![gg_bug_raster-set value to null](https://user-images.githubusercontent.com/4453449/31208806-ffc3df74-a9d2-11e7-80e5-3939e6c3c7f0.JPG)

**Comment by byezy** [comment]
![capture](https://user-images.githubusercontent.com/4742942/31210070-fa83ee8e-a9da-11e7-972d-6e1030d255ae.PNG)

**Comment by TomWaterat** [comment]
hummin!
