### ISSUE TITLE
Replications in tool run output reporting .. if easy to fix

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#214]
The output reporting text is replicated .. See example of outputs in this text file:

[Example Tool (Raster Trasform) output .txt](https://github.com/NSW-OEH-EMS-KST/grid-garage/files/1357899/Example.Tool.Raster.Trasform.output.txt)

**Comment by byezy** [comment]
added back lost line clearing handlers...

**Comment by TomWaterat** [comment]
fixed
