### ISSUE TITLE
metadata - export tips

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#216]
I haven't tested this 'stand alone' yet.. fix if anything jumps out:
![gg_bug_metadata_exporttips](https://user-images.githubusercontent.com/4453449/31213296-9de30f72-a9f1-11e7-83ce-712f0c28a201.JPG)

**Comment by byezy** [comment]
![capture](https://user-images.githubusercontent.com/4742942/31254583-fde73d66-aa74-11e7-88c5-1a0b377809e4.PNG)

**Comment by byezy** [comment]
We seem to have lost the test folder for this, it was not in ..-tests or ..-small-tests. Can you find it for me? If easier for you just email me the zip and I will do the git thing... Cheers

**Comment by TomWaterat** [comment]
@byezy replicated bug in branch 'metadata-export_tip' (note I forgot to add the 's' at the end if tips)

**Comment by byezy** [comment]
Ah no, that just seems to be a copy of the import_tip test... did you miss a commit? remember to branch from the empty master...

**Comment by TomWaterat** [comment]
I was lazy and just copied the files from the previous test.. Opening and loading a new MXD takes AGAES!! up to 5 minutes!! If you look in the 'Results' window you'll see the last GG tool that I tested.
![tool](https://user-images.githubusercontent.com/4453449/58442993-77d05280-8132-11e9-8ede-2b4c1b5ddf5e.JPG)

**Comment by byezy** [comment]
Ah, one of the tools that makes me wish i did things differently in the basetool... next version... needs testing... Code branch **i216** test repo branch **metadata-export_tips**

**Comment by TomWaterat** [comment]
Tested and working OK. Close when you've merged with master.

**Comment by byezy** [comment]
doneski
