### ISSUE TITLE
metadata - import tip files to table

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#220]
1. Change the field heading 'field_order' to 'tip_order'.
2. For tip_order field remove square brackets at beginning and end of string.
3. Also remove quotation marks 'xx' from fields.
4. Remove space between fields in list.
This is what the list should look like:
![metadata - import tip files to table](https://user-images.githubusercontent.com/4453449/32225631-08789336-be9a-11e7-9e36-99edfdde0f6d.JPG)

**Comment by byezy** [comment]
Can you update the test for this Tom (when you get the chance)? The one in the repo is from September, and is broken... if you could include the 'correct' table format that would be helpful too.

**Comment by TomWaterat** [comment]
Hi Dave.. I tried to replicate on 'C:\Data\grid-garage-tests\metadata-testing-sample-data\metadata-tests.mxd'.

I've pushed the 'grid-garage-tests' repo up with the updated mxd.. It's taking a me a while to get my head around it.. I'll have another look tomorrow.

**Comment by byezy** [comment]
push doesn't seem to have gone thru bud...

**Comment by TomWaterat** [comment]
This is the updated mxd...
![capture](https://user-images.githubusercontent.com/4453449/35303689-b9a4c882-008a-11e8-8bd1-f727f274a4f5.JPG)

**Comment by TomWaterat** [comment]
Fixed in v3.1.2 but not Master.

**Comment by byezy** [comment]
Gday Tom, sent u an email, if you can tidy up that stuff I will push up test and pull code from 3.1.2 and retest. Cheers

**Comment by TomWaterat** [comment]
Replicated in branch 'metadata-import_tip_files_to_table'.  Gap in field values is still there.. See screen grab.
![ImportTipFilesToTable](https://user-images.githubusercontent.com/4453449/58400302-ffb84d00-809d-11e9-801d-3b09fda66c1b.JPG)

**Comment by TomWaterat** [comment]
Space has been removed.. but I suspect there is a bug related to the 'tip_order' field that could be causing  Issue #216

**Comment by byezy** [comment]
That is another tool. Is this issue now resolved?

**Comment by TomWaterat** [comment]
Sorry, yes, see #216
