### ISSUE TITLE
metadata - import tip files to table - white space

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#223]
When copying the field value from the tip file the white space at the beginning is included when exported to the CSV table. See below. Is it possible to remove the white space before copying it to the output table? **Just fix it in the 3.1.1_metafix branch and I'll can do the rest.**
White space in 'tip' file:
![metadatabig01](https://user-images.githubusercontent.com/4453449/36402449-9ad3fc28-15d6-11e8-9fc8-7cdd0cd96bcc.JPG)

White space in tool output/results table file:
![metadatabig02](https://user-images.githubusercontent.com/4453449/36402456-a57c879e-15d6-11e8-99dd-fdde33f16e38.JPG)

**Comment by byezy** [comment]
Have tweaked some code and it should be fixed but we need a test case. I would have made one but I can't quite remember exactly how this tool works... fix in branch 3.1.2.2

**Comment by TomWaterat** [comment]
OK, testing now with new branch 3.1.2.2

**Comment by TomWaterat** [comment]
Space has been removed successfully. Will close
