### ISSUE TITLE
Metadata - Export Metadata crashing

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#226]
Getting the following error message:
![Bug_ExportMetadata](https://user-images.githubusercontent.com/4453449/57002602-ea1d4800-6c03-11e9-930a-1cadd8318c3d.JPG)

**Comment by byezy** [comment]
Hi Tom,

Can you replicate this using the sample data? I can't see previous steps or access P: to replicate...

I think we need to resurrect the test repo (..small-tests?) for mxds, and use relative path name settings in the mxd.

At my end, I have a structure like this:
/d/gg $ ls
grid-garage/  grid-garage-sample-data/  grid-garage-small-tests/

i.e. all of the repos side by side, in my case on d: in folder 'gg'... as I am currently on a VM with no c: access, so I will have to tweak my inputs to match yours thats all.

If this is failing only on certain datasets not in sample data, then I guess you will need to include them with the test or with the sample data...

Ta Bra

**Comment by TomWaterat** [comment]
Hi @byezy .. I added 'metadata-export_metadata' folder to the 'grid-garage-small-tests' reppo .. You'll see the error message.. says inputs and tool are not valid. If you can get it working with this subset I'll run it on all the state-wide P-drive datasets that are in the MCAS-S datapack ~100ish

**Comment by byezy** [comment]
Hi Tom, 

At the mo I only have 10.6 to test against... once I set it all up, the test ran through OK, no error.

Initially there was a parameter error showing on the tool, but once I re-pointed the input to my new table, it all validated.

![image](https://user-images.githubusercontent.com/4742942/58388962-fbbe0800-8068-11e9-94a6-2ccf202ffece.png)

And the meatadat is there...
![image](https://user-images.githubusercontent.com/4742942/58388994-56effa80-8069-11e9-83de-248fe83ece92.png)

The message you posted seems to hint at either an ArcGIS version or license error, can you try again and ensure that you have the correct license assigned.

Cheers

**Comment by byezy** [comment]
PS, Note that for this work (all of the bugs to do) I have created a branch called "3.1.2.2" in the repo. But as of now there are no code changes. Cheers

**Comment by TomWaterat** [comment]
@byezy I discovered what the problem is.. This tool (and I think some of the other Metadata Tools) will not work if you have 'Geoprocessing > Geoprocessing Options' Background Processing 'Enable' box ticked.  I'll close this issue and open another one to remind me to add this to the online help.
