### ISSUE TITLE
Polygon to raster tool - change default settings

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#228]
In the 'Field for priority field (Optional)' input box could the default be 'empty' instead of "priority_field"? Currently for the tool to work you have to delete the text in this input box.

![GG_PolyToRaster](https://user-images.githubusercontent.com/4453449/57820018-55534680-77ce-11e9-9b04-8e1e44f736c2.JPG)

**Comment by byezy** [comment]
Hi Tom,

Could you create a small test case and test this (branch 3.1.2.2). 

Should be good to go.

![image](https://user-images.githubusercontent.com/4742942/58398228-b5cc6880-8097-11e9-90e0-45bb84d45a96.png)

Cheers

**Comment by TomWaterat** [comment]
GUI is now OK.. But tool is not working. Replicated in branch 'feature-polygon_to_raster'

**Comment by byezy** [comment]
branch? 
![image](https://user-images.githubusercontent.com/4742942/58441141-cd9cfe80-8122-11e9-9de1-09f9ca7da6ee.png)

**Comment by byezy** [comment]
Hi Tom the tests that failed did not have the inputs set properly. Check the new updated mxd in the tests repo "feature-polygon_to_raster". You will still see failures, but expected ones (geometry is not polygon, field type is inappropriate).  Code branch i228, test branch feature-polygon_to_raster.

**Comment by TomWaterat** [comment]
Hi Dave, still crashing. I could not open your MXD because you saved it as ArcGIS 10.6. I've created a new one for my tests and pushed up to reppo. Can you open it?

**Comment by byezy** [comment]
Yep, downloaded. The tool is working as it should... did you read the error messages?

![image](https://user-images.githubusercontent.com/4742942/61178068-5109a500-a628-11e9-997d-b9f78800a60b.png)

**Comment by byezy** [comment]
Code ranch is **i228a**

Test branch is "feature-polygon_to_raster"

**Comment by TomWaterat** [comment]
Working, pull in.
