### ISSUE TITLE
raster - all tools

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#233]
All the raster tools (in the grid-garage master) are defaulting to 'Field for raster' = 'raster' rather than 'geodata'. 
![raster-tweak_values01_field](https://user-images.githubusercontent.com/4453449/59478713-9908a100-8e9d-11e9-891c-bb8174c2fd52.JPG)

**Comment by byezy** [comment]
yeh that was a decision we made some time ago... it was to make it clearer to the user that these tools were not generic, they required raster inputs
not a bug, by design

**Comment by byezy** [comment]
And in using this lately, I still think it's a good idea, it makes you think about your inputs...

**Comment by byezy** [comment]
In order to make this easier, I will add two new tools... search raster and search feature. This will make kicking off workflows with well known data much easier.

**Comment by byezy** [comment]
Two new tools added in branch i233, Feature-Search_for_Features and Raster-Search_for_Rasters.
These are convenience tools as mentioned above. Test branch also called i233 in the test repo.
![image](https://user-images.githubusercontent.com/4742942/60709131-10889800-9f53-11e9-82ae-10eab8cab58a.png)

**Comment by TomWaterat** [comment]
I reckon this one is good to go (merge with master). I'll just need to update all the help files.
