### ISSUE TITLE
all tools - error checking for 'format for output rasters' selection

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#239]
Trigger an error message if any of the following combinations are encountered:
[Format for output rasters = Esri Grid] + [Output File (Dataset) Workspace = Geodatabase]
[Format for output rasters = tif] + [Output File (Dataset) Workspace = folder]
[Format for output rasters = img] + [Output File (Dataset) Workspace = folder]

**Comment by byezy** [comment]
@TomWaterat 

Que???

What's wrong with these:
[Format for output rasters = tif] + [Output File (Dataset) Workspace = folder]
[Format for output rasters = img] + [Output File (Dataset) Workspace = folder]

??? They are valid, did you mean:
[Format for output rasters = tif] + [Output File (Dataset) Workspace = Geodatabase]
[Format for output rasters = img] + [Output File (Dataset) Workspace = Geodatabase]

Oh, and I think the first condition is wrong too...
[Format for output rasters = Esri Grid] + [Output File (Dataset) Workspace = Geodatabase]

Is also valid...

Lets assume the user can get this right and drop this...?

**Comment by TomWaterat** [comment]
No worries.. close.
