### ISSUE TITLE
feature - copy (from SDE database)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#241]
Feature-Search now correctly lists feature datasets in an SDE database. But when you use this search table as input into the feature-copy tool the output files lose their original names. See screen grab. @djbye do you have any SDE databases you can test with? I don't think there is any way I can copy the OEH ones.. I could look into creating one from scratch. I haven't created a test branch for this yet.
![feature-copy_SDE](https://user-images.githubusercontent.com/4453449/60849772-9ea09f00-a22f-11e9-8bce-d632eff37d0f.JPG)

**Comment by byezy** [comment]
Try using arccatalog to copy some of these with their sde names into a fgdb that we can test on. This will also highlight any naming issues that arcgis may have. Whn there's a test branch I can take a look.

**Comment by byezy** [comment]
I have taken a stab without being able to test properly. You will probably need to knock me up some test data as described above. Just name the _test branch_ **i241** as well I reckon much easier now we are branch based.

Please test on _code branch_ **i241** which contains the untested mods, never know your luck, and it gives me a better start point.

Once we get this right, the same issue with raster names will be easy to sort out too...

**Comment by TomWaterat** [comment]
Can't load this GG tool (branch i241). It's impossible to replicate the SDE names in a file gdb. I don't think it's possible to test without having an SDE to test with. We could waste a lot of time on this.. I propose we park it for now.
![GG_ErrorLoading](https://user-images.githubusercontent.com/4453449/61256866-cc4a9280-a7b1-11e9-951a-d4d15d5f4d3f.JPG)

**Comment by byezy** [comment]
no you should be able to replicate names into fgdb... why not? even if you just do a copy into an fgdb and get the base names, then use the name tools (generate, etc) to add affixes or whatever to get them looking like the sde. doable should not take a guy like you very long.

**Comment by byezy** [comment]
@TomWaterat use the master branch now. go on...

**Comment by TomWaterat** [comment]
@byezy The issue is the SDE base names have full-stops in them.. fgdb don't allow them.
![bug_SDE](https://user-images.githubusercontent.com/4453449/61515172-49da0100-aa45-11e9-85eb-c07585d0eb8b.JPG)

**Comment by byezy** [comment]
This is effectively the same issue as #224. SDE dataset names for both raster and features need work, closing this consider it merged with #224 and update 224's name to reflect this
