### ISSUE TITLE
feature - feature to raster

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#244]
Error if you don't select an 'Output File (Dataset) Workspace' location. The output location should default to the 'Output Workspace' ... which is usually a file geodatabase. Test reppo 'i244' created. See error message in fail report.

**Comment by byezy** [comment]
code i244, test i244

**Comment by byezy** [comment]
@TomWaterat  PLEASE TEST THIS AGAINST master

**Comment by TomWaterat** [comment]
Working now, thanks @djbye!
