### ISSUE TITLE
metadata - import_tip_file_to_table and export_tips

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#248]
In the test reppo i248 i created a tip table by using the 'metadata-import_tip_files_to_table' tool. The table it generated was then used as input into the 'metata-export tips' tool. The first error related to the tool looking for a 'tip_order' field which was named 'field_order' in the table. I added a new field called 'tip_order' (and copied the field values into it) which removed that error. But the tips generated were empty.

Can you use the field name 'field_order' and check to see if the 'metadata > create tips table' tool also uses this field name.

**Comment by byezy** [comment]
tips. mcass. over it!

please try code and tests in **i248**

I can barely remember how it got to this. give it a go bro

**Comment by TomWaterat** [comment]
Almost there, just a few small changes to the format of the table that the 'import tip file to table' tool generates. 
#1 Change the 'field_order' field name to 'tip_order'
#2 Remove the '[' and inverted commas around each field - shown in this screen grab.
![Capture_tip table](https://user-images.githubusercontent.com/4453449/61458510-0b453780-a9ae-11e9-91a5-78a145bb38f6.JPG)
This is what the field should look like:
![Capture_tip table_correct](https://user-images.githubusercontent.com/4453449/61458542-20ba6180-a9ae-11e9-88e0-ee192fb8d289.JPG)

**Comment by byezy** [comment]
@TomWaterat  Tom why are you wanting fields called tips? the tips are the files aren't they?
i thought about this last night, and i chose the sensible path. i guess it's an mcass thing mcass is shit those things are fields!
so at the moment don't the two tools work? i need a bit more information here, it's not clear what is broken where and why... you are showing tables from two different tools. i'm confused as to why one must look like the other as they are feeds to different tools... do a Pauline Hanson mate...

**Comment by byezy** [comment]
oh, and both tools use the sensible term 'field_order'.. so what is broken and where I guess is my question...

**Comment by byezy** [comment]
ok made those changes as requested. #2 is pretty dumb though... best leave off the brew a bit bro ;-)

**Comment by TomWaterat** [comment]
Working now.. all good.. brew helps me man.. don't knock the brew!
