### ISSUE TITLE
All tools using new describe function

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#257]
Update all tools using utils.describe

**Comment by byezy** [comment]
Test in **master**, i have not made any test repo, hope we won't need one!

**Comment by TomWaterat** [comment]
What changed in this tool? Are these all the tools that use utils.describe?
Feature    > Describe Features
Geodata  > Describe Geoadata
Raster     > Describe Rasters
Metadata > Create Tips Table

**Comment by byezy** [comment]
I think we can close this, any issues would have surfaced by now...
