### ISSUE TITLE
All tools having an output file workspace

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#259]
Check to make sure it is used in the right spot for all these tools

**Comment by byezy** [comment]
Have update many tools to hopefully work correctly.

I hope you have one of your dastardly models to test most of these automatically?

At this stage code is in **i259**

**Comment by TomWaterat** [comment]
That's awesome Dave.. might have to crack one of me lagers to get me going! Thanks heaps. I can run all the models in a batch to test this.

**Comment by TomWaterat** [comment]
All tools tested.
