### ISSUE TITLE
geodata - list workspace tables

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#26]
refactored a bit. input is now manually selected workspaces (multiple). listing is recursive into sub workspaces.  let me know what you think but seems that usage of this tool will just be to peek into a ws of concern, so keeping an input table may be a bit much methinks

**Comment by TomWaterat** [comment]
Working OK, but the 'spaces in path name' bug in ESRI code causes some headaches! .. Should we log the bug with ESRI?

**Comment by byezy** [comment]
I think that's a good idea...
