### ISSUE TITLE
raster - copy (and other raster tools)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#269]
When the output in the 'raster > copy' tool (and all the other raster tools) is set to a file gdb geotiff files are renamed with "_tif" at the end. See table below and test branch i268.
![Bug_RastCopy](https://user-images.githubusercontent.com/4453449/61876609-9f744900-af30-11e9-8b3a-ec8021fe34d9.JPG)

**Comment by byezy** [comment]
**i268/i268**
Should be right now. Also checked feature copy.

**Comment by TomWaterat** [comment]
Thanks Dave, now working with all raster tools and feature copy.  Close when you've merged back.
