### ISSUE TITLE
raster - to ascii

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#270]
I didn't have time to set up a test branch.. let me know if you can't replicate. When using **i268** gg code branch.. Getting the following error message when running tool using sample data grids as inputs:

_['Traceback (most recent call last):\n', ' File "D:\\gg\\grid-garage\\base\\base_tool.py", line 667, in do_iteration\n  res = func(row)\n', ' File "D:\\gg\\grid-garage\\tools\\raster\\to_ascii.py", line 73, in copy\n  arcpy.RasterToASCII_conversion(ras, ras_out)\n', ' File "c:\\program files (x86)\\arcgis\\desktop10.4\\arcpy\\arcpy\\conversion.py", line 255, in RasterToASCII\n  raise e\n', "ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000885: Output ASCII raster file: R:\\TomBarrett\\Data\\grid-garage-sample-data\\OUTPUT_ASCII_\\T0825_04_SPOT5_WoodyExtent_Armidale_sml_asc's does not have a file extension.\nFailed to execute (RasterToASCII).\n\n"]

**Comment by byezy** [comment]
**i270/i270** Checked ascii files, looked ok. had to remove from repo as too large. caused a headache, just when you think github can't get more difficult, you find stuff like this:
`git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch <file/dir>' HEAD`

**Comment by TomWaterat** [comment]
Yep.. all working fine now.. Thanks Dave.
