### ISSUE TITLE
results table - field name for output data 

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#271]
I checked the field name for output data location in the results table of each tool. This Excel file ([GG_Testing.xlsx](https://github.com/NSW-OEH-EMS-KST/grid-garage/files/3449446/GG_Testing.xlsx)) lists those that need to be changed to reflect the type of output data e.g. raster or feature. In summary: 

- 2 need to be changed from geodata to feature 
-- feature>clip
-- feature>copy

- 6 need to be changed from geodata to raster
--feature>feature to raster
--feature>polygon to raster
--raster>block statistics
--raster>build attribute table
--raster>to ascii)

**Comment by byezy** [comment]
**i271/i271** The last couple of raster tools listed looked right, not sure why you thought needed a fix, so please check again to see if I have overlooked something. Started a test repo but didn't get to test everything.

**Comment by TomWaterat** [comment]
Thanks Dave.. All good now..
