### ISSUE TITLE
grid - tweak values (and other tools)

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#273]
Getting error messages when output file name has greater than 13 characters. This should not be an issue if you select 'format for output raster = tif'. See branch i272 in tests (this issue was allocated 273 for some reason it skipped 272!).

Error message when using raster-tweak values:
['Traceback (most recent call last):\n', ' File "D:\\gg\\grid-garage\\base\\base_tool.py", line 667, in do_iteration\n  res = func(row)\n', ' File "D:\\gg\\grid-garage\\tools\\raster\\tweak_values.py", line 146, in tweak\n  ras.save(r_out)\n', 'RuntimeError: ERROR 010240: Could not save raster dataset to D:\\gg\\grid-garage-tests\\Out\\MCASS_StudyAreaTemplate30m_sml_Suffix_to_make_name_greater_than_13_tif with output format GRID.\n']

Error message when using raster-copy:
['Traceback (most recent call last):\n', ' File "D:\\gg\\grid-garage\\tools\\raster\\copy.py", line 111, in copy\n  arcpy.CopyRaster_management(ras, ras_out, self.config_keyword, self.background_value, self.nodata_value, self.onebit_to_eightbit, self.colormap_to_RGB, self.pixel_type, self.scale_pixel_value, self.RGB_to_Colormap, None, self.transform)\n', ' File "c:\\program files (x86)\\arcgis\\desktop10.4\\arcpy\\arcpy\\management.py", line 12737, in CopyRaster\n  raise e\n', 'ExecuteError: Failed to execute. Parameters are not valid.\nERROR 000472: Name of single band grid cannot have more than 13 characters\nFailed to execute (CopyRaster).\n\n']

**Comment by byezy** [comment]
code in **master** test in **i272**

**Comment by TomWaterat** [comment]
All good.. thanks Dave
