### ISSUE TITLE
gg error reporting

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#277]
When running the 'Feature > Polygon to Raster' tool the 'geodata' field in the gg error report is not returning the data path. Instead it is returning the fields.

To replicate this I just changed the geodata path name in the input table (shown here). And then ran the Feature > Polygon to Raster tool.
![GG-ErrorBug01](https://user-images.githubusercontent.com/4453449/63321080-097ee300-c363-11e9-8a79-2e6dbdbf5f48.JPG)

This is the error table with the bug:
![GG-ErrorBug02](https://user-images.githubusercontent.com/4453449/63321090-0edc2d80-c363-11e9-94cc-7ff025ffe28c.JPG)

**Comment by byezy** [comment]
This crept in when making the source data field name match the data type to make the proc streams clearer... the fail table should now hold the same input data field name as the source table for the tool... (this should be consistent with all tools so raster->raster, feature->feature etc.)
i.e.:
![image](https://user-images.githubusercontent.com/4742942/63390972-3af3bf00-c3f4-11e9-96e0-bd8fa9abec4a.png)

code/test **i277/i277**

**Comment by TomWaterat** [comment]
Thanks Dave.. all good now. Closing now.
