### ISSUE TITLE
geodata - compare extents

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#28]
ready for a test

**Comment by TomWaterat** [comment]
Only fails when the spatial references are different.. @byezy Can you confirm that both datasets need to be in the same projection for the comparison to work?

**Comment by byezy** [comment]
no it shouldn't. should only fail if srs is 'unknown' otherwise the extent is transformed. the result of the transformed extent is also included in the output table (srs name + extent cords)... @TomWaterat  I will check the test shortly.

**Comment by byezy** [comment]
bug found and fixed. test updated.

**Comment by TomWaterat** [comment]
Re-ran tests too.. works OK
