### ISSUE TITLE
Search Geodata Interface

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#3]
Tom's questions re search interface:

![untitled](https://cloud.githubusercontent.com/assets/4742942/20045246/94944836-a4f3-11e6-8ac4-c6ef0dda66b9.png)

And my reply:

![untitled2a](https://cloud.githubusercontent.com/assets/4742942/20045374/abb28a0e-a4f4-11e6-929b-9560f73e43c6.png)

TOM, PLEASE NOTE THE USELESS option control BELOW THE OUTPUT WORKSPACE PARAMETER BUT BEFORE THE VALUE... THIS IS DUE TO RUNNING IN 10.1, THE PARAMETER DISPLAYS PROPERLY IN 10.4

**Comment by byezy** [comment]
@TomWaterat : Hi Tom, if you feel strongly about point 1, please log a new issue as an enhancement and I will implement it, you are the boss ;-) but think about my comments. FYI I've been using the tool and an extra mouseclick does not seem to be an issue and helps the user focus on the task.

**Comment by TomWaterat** [comment]
All good.. happy for this to be closed:)
