### ISSUE TITLE
raster - reproject

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#31]
needs testing.  test case should be there also.

**Comment by TomWaterat** [comment]
Getting an error "FAIL:   File "C:\Data\gg3\grid-garage-3\base\base_tool.py", line 50, in error_handler|    yield|Incorrect value for spatial reference name".. I tried re-defining the projection from "GDA_1994_Albers" to the ESRI standard proj "GDA_1994_Australia_Albers".. But still getting the error. See test MXD.

**Comment by byezy** [comment]
Hi Tom, once again at the mo, could u pls check the gui side, start a new issue for any calc bugs. cheers
