### ISSUE TITLE
raster - resample

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#32]
to test sensibly.  test case should be there also.

**Comment by TomWaterat** [comment]
Working OK, except for the two grids from the ABARES data pack (rain and sheep layers)..  I don't think they are resampling correctly.. see attached screen grab.. 
![resample](https://cloud.githubusercontent.com/assets/4453449/20472343/1424e226-b00d-11e6-99e8-cec0ddb3191c.JPG)
They are Albers projection and I think this has something to do with it.. Will only spend time on this if it becomes a problem with other layers. @byezy what do you reckon?

**Comment by TomWaterat** [comment]
@byezy Sorry man.. this test folder went up to 54MB... If it takes too long to download I can delete some of the GDBs and re-commit, push etc..

**Comment by TomWaterat** [comment]
In manual (and help) specify that the rasters need to be in the same projection as that set in the Geoprocessing 'Environments'...
