### ISSUE TITLE
raster - transform - gui

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#35]
Based on the GUI for GG2.. Only the 'STRETCH' function requires the "Stretch to Max/Min value" input parameter. Disable these when other functions are selected.

**Comment by byezy** [comment]
Fixed. Requires testing (interface behaviour). Note the tool may still have calc bugs, addressing in separate issue..

**Comment by TomWaterat** [comment]
GUI behaviour looks fine.. fixed.
