### ISSUE TITLE
raster - transform 

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#36]
Error message:
FAIL:   File "C:\Data\gg3\grid-garage-3\base\base_tool.py", line 50, in error_handler|    yield|'unicode' object is not callable
>>See test MXD

**Comment by TomWaterat** [comment]
Error when performing a stretch.. see MXD.

ERROR MESSAGE:
FAIL:   File "C:\Data\gg3\grid-garage-3\base\base_tool.py", line 50, in error_handler|    yield|Argument nodata_to_value: Integer types do not support NaN or infinite values.

**Comment by byezy** [comment]
i think you forgot to push this test into the repo - nothing in the mxd...

**Comment by TomWaterat** [comment]
Try now.. my GitBash was pointing to the old URL repo! I had to point it to the new one with the command 'git remote set-url origin https://github.com/NSW-OEH-EMS-KST/..repo name'

**Comment by TomWaterat** [comment]
New error .. opened a new issue .. see #91
