### ISSUE TITLE
raster - zonal counts - gui

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#39]
Need to be able to select the feature in the 'Zone Features' input box - as you can in the GG2 version.
![zonal counts](https://cloud.githubusercontent.com/assets/4453449/20510406/2e3cdb66-b0c4-11e6-9e0c-4d358f4cf59b.JPG)

**Comment by byezy** [comment]
resolved. polygon selection from map or other...

![untitled](https://cloud.githubusercontent.com/assets/4742942/20870078/6265b5a0-bad5-11e6-83c7-d96ee4aea79f.png)

**Comment by TomWaterat** [comment]
'Field of Interest' is not providing a drop-down list of fields from the feature dataset.
![gg3 zonal count_gui2](https://cloud.githubusercontent.com/assets/4453449/20870612/708dd2fc-badf-11e6-8538-cbf06bd9e8af.JPG)

**Comment by byezy** [comment]
a lot of code has been added, but believe this tool still buggy

**Comment by byezy** [comment]
yep this is a pain, i dont think we tested v2 tool with shapefiles, needs a bit of work this one...

**Comment by byezy** [comment]
Hi Tom, can you please test the gui part of this tool... then please make new issues for any calc bugs, there will be some...

**Comment by TomWaterat** [comment]
Testing and adding new issues.
