### ISSUE TITLE
Search Geodata - Spaces in Workspace Name

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#4]
![untitled](https://cloud.githubusercontent.com/assets/4742942/20045456/5c2a3db4-a4f5-11e6-8fae-b35961cef700.png)

Believed to be a bug in 10.1. Will test and verify.

**Comment by byezy** [comment]
Hi Tom, could you retest when 10.4 is up and running. Cheers

**Comment by byezy** [comment]
This bug is still present in 10.4. Essentially any search of a workspace with a space in the name at the top-level will fail. It seems the failure only occurs at the top-level, any nested folders with spaces in their name do not fail. WORKAROUND: Do not select folder's with spaces in names to search through. Instead select the next parent folder that is properly named.

**Comment by TomWaterat** [comment]
Document this in manual.
