### ISSUE TITLE
parameter - workspaces - has white spaces

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#42]
When there are any white spaces in the 'workspaces' parameter all the GG V3 tools crash - without any error message and without producing a 'Result_Table_FAIL' file.  

Keep this issue live until it is resolved.

**Comment by TomWaterat** [comment]
Have you tried using the 'r' parameter or "raw string", described in this link (and screen grab)? https://www.e-education.psu.edu/geog485/book/export/html/59
![raw string](https://cloud.githubusercontent.com/assets/4453449/20610350/715f5548-b2ec-11e6-8e69-f98c615f48eb.JPG)

**Comment by byezy** [comment]
??  Not every tool has a 'workspaces' parameter what parameter/tool do u mean? what do u mean every tool crashes ??  show me a test mxd please...

**Comment by TomWaterat** [comment]
Sorry @byezy, you're right.. it is just the geodata - search tool.. see replication of bug in MXD.

**Comment by byezy** [comment]
This is an ESRI issue for the moment. Need to document in the manual that if the root folder to search into has a space the search will fail. Folders with spaces in the name that are not root seem to be correctly processed so workaround is to search from a higher folder with no spaces...

**Comment by TomWaterat** [comment]
OK, will close and leave 'bug' label.
