### ISSUE TITLE
general - 64bit and background processing

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#43]
Some of the GG3 tools can be run in the background, i.e. the 'Always run in foreground' option in the Tool Properties 'General' tab, is un-checked. But some cannot, the option is always checked. The option is greyed out so it cannot be changed. Ideally it would be good if the tools could be run in the background if this is possible!

This screen grab shows the option ticked (and greyed out) for Geodata>Search:
![properties](https://cloud.githubusercontent.com/assets/4453449/20612078/f9048ed8-b309-11e6-99da-80dd6d61391d.JPG)

This blog discusses 64bit and background processing for python scripts..
https://blogs.esri.com/esri/arcgis/2012/11/12/python-scripting-with-64-bit-processing/

This is some generic stuff from ESRI.. not sure if it helps:
http://desktop.arcgis.com/en/arcmap/10.3/analyze/creating-tools/running-custom-tools-in-background-2.htm

**Comment by byezy** [comment]
Hi Tom, with Python tools the run mode is set in code... so it has to be one or the other. I will set them all to background, except the add to display tool. If the user has the run-in-back... geoproc option set then they will always be in background.

**Comment by TomWaterat** [comment]
Awesome.. thanks Dave. I'll also let users know in user manual.

**Comment by byezy** [comment]
Hi Tom, just checked they should already all be set ready for bak proc... you have to set the option in arcmap geoproc options though or else it will go foreground.

**Comment by byezy** [comment]
the exception is the display data tool.

**Comment by byezy** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4742942/20654942/e7315ff0-b571-11e6-8890-870bf086de5c.png)

this is my understanding of how esri have done this anyway.... let me know if wrong...

**Comment by TomWaterat** [comment]
In addition to the display data tool the following tools have the 'Always run in foreground' tick box selected by default (when your right-mouse-click and select 'properties') .. even when you select the 'run in background' geoprocessing setting:
Feature - Rasterise by Table
Geodata - Describe
Geodata - List Workspace Tables
Geodata - Search
Geodata - Select

**Comment by byezy** [comment]
Done

**Comment by TomWaterat** [comment]
Tested and working
