### ISSUE TITLE
general - reporting on geodata path - issue with different drive letters

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#44]
To avoid the issue of network files mapped to different drive letters, e.g. P-Drive on one computer vs same folders mapped to X-Drive on another computer. could the Search or Describe tool also return the UNC path?  

Paths are described here: http://desktop.arcgis.com/en/arcmap/10.3/map/working-with-arcmap/referencing-data-in-the-map.htm 

Although this link does mention there are disadvantages of using the UNC path for local files.

**Comment by byezy** [comment]
Hi Tom, maybe not so simple... can you find in arccatalog a dataset that refers to it's data source by UNC??? So far I can't. The python code can only get show what it is given (so far by my investigation). 

I don't see this as an issue, I would see the fact that someone wants to reference the same files on multiple machines for processing as more of an issue...  thoughts??

**Comment by TomWaterat** [comment]
Agree.. close this one. Just alert users in user manual.
