### ISSUE TITLE
geodata - compare extents

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#48]
Add the text "(aoi)" after "Data set to compare with" .. as per the attached image.

![gg3 compare extents_gui](https://cloud.githubusercontent.com/assets/4453449/20779587/8be9b34a-b7c9-11e6-8e99-71a29689d8b6.JPG)

**Comment by byezy** [comment]
done, ecept it became

Dataset (Area of Interest) to compare with

**Comment by TomWaterat** [comment]
Cool.. updated manual and help xml.
