### ISSUE TITLE
raster - calculate statistics - gui

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#49]
GUI just needs tidying up.. I think.. See attached.
![gg3 calculate statistics_gui](https://cloud.githubusercontent.com/assets/4453449/20780963/6caa19b6-b7d3-11e6-8aa3-61e1c039f13d.JPG)

**Comment by byezy** [comment]
parameter should now only accept POLYGON features

**Comment by TomWaterat** [comment]
Yep, tested and now only accepts POLYGON feature.. Is there a reason why the EOI parameter is grey, and has a space below it? Maybe tidy up so it looks like the others.

**Comment by TomWaterat** [comment]
Sorry @byezy .. bloody ArcGIS was picking up old code.. looks and works fine now..
