### ISSUE TITLE
Search geodata - table column header

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#5]
Reported by @TomWaterat 
![untitled](https://cloud.githubusercontent.com/assets/4742942/20045736/f9e876e0-a4f7-11e6-87a1-2995767e278c.png)

I have seen this in testing too, went away when trying to find the issue, but I may have been in 10.1 and it went away once back on 10.4.

Needs investigating on 10.4.

**Comment by TomWaterat** [comment]
Tested in 10.4.1 and has been fixed. Close
