### ISSUE TITLE
raster - zonal count - gui

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#50]
Change 'Zone Values' to 'Zone Values to Count'
![gg3 zonal count_gui](https://cloud.githubusercontent.com/assets/4453449/20781257/9ede8226-b7d5-11e6-8fe9-37daeac96836.JPG)

**Comment by byezy** [comment]
Labels are now:
...
Zone Features
Field of Interest
Values to Count

Which I think is pretty clear??

**Comment by TomWaterat** [comment]
Cool.. updated in manual.
