### ISSUE TITLE
raster - reproject 

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#51]
The old tool (GG2) had the following option.. do we need to consider this in GG3?

**Transformation Override (optional):** If the datum for the input spatial reference is different to datum for the new spatial reference then ArcGIS will need to convert the datum using a ‘transformation’. The first time you run this tool it will select a default transformation (if nothing is entered into this text box).  If you want to use a different transformation then you must run the tool again and specify the transformation to over-ride the one chosen by ArcGIS using the following syntax: ‘old transformation1: replacement transformation1, old transformation2: replacement transformation2’ and illustrated in Figure 7 below.  
 
Figure 7 Example of a transformation override, where the transformation ‘AGD_1966_To_GDA_1994_11_NTv2’ replaces the default transformation chosen by ArcGIS which was ‘AGD_1966_To_GDA_1994’.

**Comment by byezy** [comment]
i think so. will add it.

**Comment by byezy** [comment]
Has been added, but still bugs. This issue to close for the bug issues.

**Comment by TomWaterat** [comment]
Tested and working OK.. Have not tested 'transformation override' option yet..
