### ISSUE TITLE
geodata - gui

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#52]
When the user ticks the 'Any' file type.. This tick box needs to be turned off when they try to tick any of the other file type tick boxes.. Alternatively.. If ticking all of the tick boxes is the same as ticking the 'Any' option.. then maybe the 'Any' tick box is not needed?
![gg3 geodata - gui](https://cloud.githubusercontent.com/assets/4453449/21084725/08fc9056-c05c-11e6-8e78-673f836e4f39.JPG)

**Comment by byezy** [comment]
"Any" option has been removed. 'Select All' must now be used. May slow script down insignificantly but it does clarify things. Good suggestion.

**Comment by TomWaterat** [comment]
Could another option be to use a radio box where the user can only select ONE of two option: 1) Any or 2) Select data type.. then if they choose 'Select data type' then they can select one or more types.... ALSO the 'space in the path folder name' bug would not affect the 'Any' option??? Feasible??

**Comment by byezy** [comment]
Lets see if there actually are performance issues first ay..?  Spaces issue should be gone now.

**Comment by byezy** [comment]
Take another look at this mate I think we are getting into the realm of dickhead proofing the tools again and out-of-scope for our resources. Pretty sure most of our users will get that if they select "Any" that's what they'll get regardless of other choices... and radio box idea might be doable but don't I believe it worth the time at this stage. cheers

**Comment by TomWaterat** [comment]
OK, leave as a low priority suggestion for now.
