### ISSUE TITLE
raster - zonal counts gui2

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#54]
If the user leaves the 'Values to Count' input parameter blank.. can this default to counting all values?  If this is the case then remove the green dot (i.e. does not require a value).

![gg3 raster - zonal count gui3](https://cloud.githubusercontent.com/assets/4453449/21122357/b1fd1030-c125-11e6-8fc4-eb4e3f86d996.JPG)

**Comment by byezy** [comment]
Is that a good idea??? I can imagine arcgis taking a LONG time to do this. What about floating point rasters...??? It's a can of worms which I thibk we don't need... best to reclassify etc n take a diff approach  methinks but if u can show me a USEFUL use-case we can try it...

**Comment by byezy** [comment]
Removed
