### ISSUE TITLE
Raster format validation

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#57]
Be nice to validate raster format against workspace type...

**Comment by TomWaterat** [comment]
Sounds good.. do when time permits.

**Comment by byezy** [comment]
ahh what a nightmare, cant get the updatemessages method in the base tool class to behave. can only get it to throw and error n create havoc... have to come back to it when I can...

**Comment by byezy** [comment]
@TomWaterat dude I want to close this for the moment. my feeling is we do not enhance gg at all for arcgis 10.x any more. The time should go into GGJ, or into a new GG for ArcPro, both of which would be using Py3 and benefit mutually.
