### ISSUE TITLE
Idea for manual - Advice for when to reproject

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#59]
Many of the functions work better if the input geodata is in the same projection as the 'Geoprocessing > Environment' settings.. Include advice to this affect in manual.

**Comment by byezy** [comment]
??  What does this mean Tomski? Which functions? Work better? How?

**Comment by TomWaterat** [comment]
That's what I'm going to find out!  This is just one example where the results can be unexpected (output from 'raster - tweak values':
![gg3 raster - tweak values_proj](https://cloud.githubusercontent.com/assets/4453449/21170659/bc910498-c21a-11e6-9037-1502af55a097.JPG)

**Comment by byezy** [comment]
Nah this is no good. Looks like arc is doing OTF reproj of the source but our tool is generating a raster in the data pane's SR and calcing bounds per the pane SR too..? If this is in the repo for the tests I'll try to take a look shortly. Cheers

**Comment by TomWaterat** [comment]
OK, close this one.. it has been reported as a bug in #58
