### ISSUE TITLE
CSV Output

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#6]
Reported by @TomWaterat 

![untitled](https://cloud.githubusercontent.com/assets/4742942/20045803/5e1cd304-a4f8-11e6-8135-4ff8628f04fe.png)

I believed I had fixed this, must have been lost. Easy fix, will revisit and remove spaces.

**Comment by TomWaterat** [comment]
Tested and has been fixed. Close
