### ISSUE TITLE
Raster compression parameters

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#61]
Look into different types of compression for geotiffs.. see links:
http://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/raster-compression.htm
and
https://blogs.esri.com/esri/arcgis/2010/12/21/rasters-get-speed-save-space/

See if MCAS-S can still use these compressed geotiffs.

**Comment by byezy** [comment]
Hi Tom,

Exactly what compression do you wish to support...? I think we can make the tools make/use the compressed formats if required but the question is MCASS... can you convert a couple of rasters within an MCASS project and see how...? LZW might be a reasonable choice if it works with MCASS. Cheers

**Comment by byezy** [comment]
Hi Tom,

My rasters seem to be getting compressed anyway. Using the copy tool tiff reports using LZW and uncompressed size 145k size on disk about 33k. note my env. setting was LZ77 so irt seems arcgis is just doing it's own thing. check on your side if this the case.

**Comment by TomWaterat** [comment]
My system is doing the same thing.. all TIFF outputs use LZW compression.. Environment Settings is set to LZ77.. So maybe it's not an issue?

**Comment by byezy** [comment]
To be thourough, should allow user to specify where appropriate. Might be sticky but worth a quick snif to see.

**Comment by byezy** [comment]
Hi Tom, would have been nice, but with time now short, SUGGEST that you make a note re raster compression in the help.... AND THAT IF REQUIRED ENVIRONMENTS SHOULD BE SET ACCORDINGLY...

pass the buck, but no choice...

**Comment by byezy** [comment]
if u agree pls close this

**Comment by TomWaterat** [comment]
Set to update documentation..
