### ISSUE TITLE
features - copy

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#66]
This is a new tool.. Needs explanation.
![gg3 features - copy](https://cloud.githubusercontent.com/assets/4453449/22134645/c9d48322-df1c-11e6-8010-10f22de89db9.JPG)

**Comment by byezy** [comment]
No I think it was an existing tool, but this time implemented fully... last version did not have full parameters I think - anyway see this it's the way to properly control feature class copies i think...?

http://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/copy-features.htm
