### ISSUE TITLE
geodata - copy

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#68]
I don't think this is a bug.. Just confirming that you cannot use this tool to copy from one GIS file type to another, for example you cannot copy a Shapefile into a feature class in a Geodatabase.  See fail table in test MXD.

**Comment by byezy** [comment]
yep, for that (changing formats) you need to use the raster-copy and feature-copy. so this tool will really only copy into same format/workspace type...
