### ISSUE TITLE
Describe Geodata - Column Sync

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#7]
Describe result table can become confused after describing certain datasets which likely sneak in a comma or other control character in their return.

[Book1.xlsx](https://github.com/byezy/grid-garage-3/files/574426/Book1.xlsx)

Needs to be fixed

**Comment by byezy** [comment]
This may (or may not) have been fixed during a bugfix on the results library. Have not been able to reproduce this error using the sample data:
1/ Either update the sample data with a dataset that causes this behaviour,
OR
2/ Close until this can be reproduced

**Comment by TomWaterat** [comment]
Could not replicate. Will close until it occurs again.
