### ISSUE TITLE
gg3 - toolbox install

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#70]
Be good to allow user to install gg3 toolbox - so it is always visible in ArcToolbox window.

**Comment by byezy** [comment]
This must be an arcgis thing. did a quick search could not find how to do it...

**Comment by TomWaterat** [comment]
@byezy  I found this thread:

http://gis.stackexchange.com/questions/130772/permanently-add-a-python-toolbox-to-arctoolbox

Any good?

**Comment by byezy** [comment]
normal template mod sounds easier, but both approaches might fall over due to c: lockdown by IT. will have to tool around and test this. when time permits/
