### ISSUE TITLE
raster - block statistics

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#73]
Crashed.. MXD has been pushed up into repo.

**Comment by byezy** [comment]
tested n pushed up

**Comment by TomWaterat** [comment]
Pushed new version up.. Update: When you specify a TIF as the output .. the second time you run the tool it over-rides the old version.. causes an error if you have loaded the old TIF into ArcMap

**Comment by TomWaterat** [comment]
Working fine!
