### ISSUE TITLE
Grouped Optional Inputs - Affixes and Options

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#77]
Hi Tom,

Please take a look at tools that use the new filename affix inputs... I have grouped them. It means they show at the bottom and are collapsed by default... I think it looks cleaner. What do you think???

cheers
![capture](https://cloud.githubusercontent.com/assets/4742942/24386760/1c35a342-13bd-11e7-9430-02b4e1d286e9.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4742942/24386761/1c3632a8-13bd-11e7-88e5-8df4c1bbda17.PNG)

**Comment by byezy** [comment]
Tom, this can really help clean up the GUI - I only discovered this!! For example I have done the calculate stats tool which has lots of options. you get as follows: (BTW This then makes the GUI forms much more consistent with "Options" at the bottom... I'm likin' it!" You???
![capture](https://cloud.githubusercontent.com/assets/4742942/24387049/a0012a60-13be-11e7-945f-10f3e9e994b4.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4742942/24387048/9ffcbc0a-13be-11e7-946c-e0cb0686196a.PNG)

**Comment by byezy** [comment]
for the aggregate tool...

![capture](https://cloud.githubusercontent.com/assets/4742942/24387371/751267b8-13c0-11e7-8e63-325da12dad86.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4742942/24387372/75129bf2-13c0-11e7-9754-954d8b6151e9.PNG)

**Comment by byezy** [comment]
clip tool... guess it's happening now...
![capture](https://cloud.githubusercontent.com/assets/4742942/24387539/739eed92-13c1-11e7-9af6-a00c0d9688c1.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4742942/24387540/73b8062e-13c1-11e7-9769-b21f1384adc9.PNG)

**Comment by byezy** [comment]
cleaned the raster copy tool up nicely...
![capture](https://cloud.githubusercontent.com/assets/4742942/24387666/2dacdb0e-13c2-11e7-913f-af019eee2116.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4742942/24387665/2daaae7e-13c2-11e7-8697-f9706b7d5f74.PNG)

**Comment by byezy** [comment]
well that's them done anyway, hope u like it if not then not too hard to roll back.. last couple commits...

**Comment by TomWaterat** [comment]
@byezy  Love it!  Nothing worse than a crowded GUI!
