### ISSUE TITLE
gg3 versioning

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#79]
What do you reckon about calling the final beta version 3.01?  With the following features being added to v3.00:

> Implementation of the log file 
> Adding prefix and suffix to outputs
> Collapsing the some of the user input options to clean up the GUI

**Comment by byezy** [comment]
can do. betas are usually 0.xxx so we are really past that ... it has been getting used and bugfixed so 3.01 sounds good!! where does this need to appear???

**Comment by TomWaterat** [comment]
Cool.. Just need to update in the ArcGIS help.. I can do this.
