### ISSUE TITLE
Display Geodata

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#8]
Reported by @TomWaterat 

![untitled](https://cloud.githubusercontent.com/assets/4742942/20046048/2eb2278e-a4fa-11e6-962f-33259bbc7565.png)

I have seen this in 10.1, resolved in 10.4.

Needs checking again on 10.4

**Comment by byezy** [comment]
Hi Tom, could you check this in 10.4 when you can. Cheers

**Comment by TomWaterat** [comment]
Could not replicate in 10.4
