### ISSUE TITLE
raster - copy

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#81]
When you specify a folder 'Output workspace' all output files are given the '_tiff' suffix.. This should only happen if there is a file with the same name present. See mxd in tests.

**Comment by byezy** [comment]
so we go in circles... can't fix this and the other renaming issue too... this is what the creatuniquename etc. esri calls give us. I don't consider this important at this time, as long as unique names are made... or would you rather it crash when can't overwrite... one way or the other...!

**Comment by byezy** [comment]
I think I've finally worked out how to use their bloody calls... can you try the ras copy and a few other tools to check this...?
![capture](https://cloud.githubusercontent.com/assets/4742942/24435958/220fd2a2-1484-11e7-8687-90cc0288fa8f.PNG)

**Comment by TomWaterat** [comment]
Output files are now being overwritten.. Maybe we could leave it at this?? They have the option of changing the output names now.. i.e. adding prefix/suffix.  

Whatdoyareckon?

**Comment by byezy** [comment]
so I think that depends on the user gp env settings? if they have 'overwrite' set true it overwrites... so from my side I think fixed, or am I missing something...?

**Comment by TomWaterat** [comment]
Not an issue
