### ISSUE TITLE
Format for output rasters

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#85]
Would it be possible to restrict the 'Format for output rasters' to only legal outputs determined by the 'Output workspace' selected? E.g. If they select a folder then they cannot use 'ESRI Grid' as an output.

Current status - gg3 will crash without producing a FAIL table.

**Comment by byezy** [comment]
can u show me a test where gg3 behaves like that?

**Comment by byezy** [comment]
it can be done but needs code, probably not today...

**Comment by byezy** [comment]
this issue was already in as an enhancement issue #57. closing as duplicate
