### ISSUE TITLE
testing - build system tests for muliple tools with ModelBuilder

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#88]
This will save time because it takes SOOOO long to open a new ArcGIS project!!

**Comment by TomWaterat** [comment]
Idea - When running the tests have two versions: 1) outputs to File Geodatabase and 2) outputs to folders.

**Comment by byezy** [comment]
I think we should go the python route, fck modelbuilder, but this is time I just don't have at the moment. or use the models you do, export to python script then we can go from there - knock up a system. still gonna need work to sort out success/failures/reasons...

**Comment by TomWaterat** [comment]
Revisit when I get the time to learn python.
