### ISSUE TITLE
csv not being removed

### ISSUE THREAD

**Issue by byezy** [NSW-OEH-EMS-KST/grid-garage-3#9]
intermediate csv is not being removed when final output is to a gdb

**Comment by byezy** [comment]
CSV is being removed on dev machine. Test on Tom's machine, close if OK.

**Comment by TomWaterat** [comment]
Tested and has been fixed. Close

**Comment by byezy** [comment]
Hi Tom, The csv is being deleted this end just re-tested... can you give me the test that made you reopen this?

**Comment by TomWaterat** [comment]
Working
